/**
 * Acceptance criteria 1-4 and 6, against fixtures built on the fly.
 *
 * Every fixture is a real git repository with real commits, because the signals under
 * test (nested-repo discovery, churn) do not exist without one.
 */

import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';

import { inventory } from '../src/inventory.js';
import { extract } from '../src/extract.js';
import { rank } from '../src/rank.js';
import { digest } from '../src/digest.js';

let root: string;

function git(cwd: string, ...args: string[]): void {
  execFileSync('git', ['-C', cwd, ...args], { stdio: ['ignore', 'ignore', 'ignore'] });
}

function initRepo(dir: string): void {
  fs.mkdirSync(dir, { recursive: true });
  git(dir, 'init', '-q');
  git(dir, 'config', 'user.email', 'fixture@test.local');
  git(dir, 'config', 'user.name', 'fixture');
}

function write(file: string, body: string): void {
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, body);
}

function commitAll(dir: string, message: string): void {
  git(dir, 'add', '-A');
  git(dir, 'commit', '-q', '-m', message, '--allow-empty');
}

beforeAll(() => {
  root = fs.mkdtempSync(path.join(os.tmpdir(), 'repo-tour-fixture-'));

  // ---- outer repo -------------------------------------------------------
  initRepo(root);

  // A small, high-churn structural file. This is the `manifest.yaml` shape.
  write(path.join(root, 'manifest.yaml'), 'name: fixture\nversion: 1\n');

  // A huge, single-commit data file with no importers. This is the benchmark-exhaust shape.
  write(
    path.join(root, 'reports/bench_dump.json'),
    JSON.stringify({ rows: Array.from({ length: 4000 }, (_, i) => ({ i, v: i * 2 })) }, null, 2),
  );

  write(
    path.join(root, 'src/core.py'),
    [
      'import os',
      'from .helpers import shout',
      '',
      'MAX_RETRIES = 3',
      '_PRIVATE = 1',
      '',
      '',
      'def run(job):',
      '    return shout(job)',
      '',
      '',
      'def _internal():',
      '    pass',
      '',
      '',
      'class Engine:',
      '    def start(self):',
      '        pass',
      '',
      '    def _stop(self):',
      '        pass',
      '',
    ].join('\n'),
  );

  write(
    path.join(root, 'src/helpers.py'),
    ['def shout(s):', '    return str(s).upper()', ''].join('\n'),
  );

  // Two more importers of helpers.py, so in-degree is a real number.
  write(path.join(root, 'src/alpha.py'), 'from .helpers import shout\n');
  write(path.join(root, 'src/beta.py'), 'from src.helpers import shout\n');

  write(
    path.join(root, 'src/app.ts'),
    [
      "import { shout } from './util.js';",
      "import express from 'express';",
      '',
      'export interface Options { loud: boolean }',
      'export type Name = string;',
      '',
      'export function greet(n: Name): string {',
      '  return shout(n);',
      '}',
      '',
      'export const VERSION = 2;',
      '',
      'export class Server {',
      '  listen() {}',
      '  _private() {}',
      '}',
      '',
      'function notExported() {}',
      '',
    ].join('\n'),
  );

  write(path.join(root, 'src/util.ts'), 'export function shout(s: string) { return s.toUpperCase(); }\n');

  // Things that must be floored to zero (criterion 2).
  write(path.join(root, 'package-lock.json'), '{"lockfileVersion": 3}\n');
  write(path.join(root, 'vendor/leftpad/index.js'), 'module.exports = function () {};\n');
  write(path.join(root, 'dist/bundle.js'), 'console.log(1);\n');
  write(path.join(root, 'src/schema_pb2.py'), 'DESCRIPTOR = None\n');
  write(path.join(root, 'src/marked.py'), '# @generated by a tool\nX = 1\n');

  // A document that lives in a `specs/` folder and is NOT a test.
  write(path.join(root, 'specs/design.md'), '# Design\n\nProse, not a test.\n');

  // A real test file.
  write(path.join(root, 'tests/test_core.py'), 'def test_run():\n    assert True\n');

  commitAll(root, 'initial');

  // Churn: touch manifest.yaml many times, the dump never again.
  for (let i = 0; i < 9; i++) {
    write(path.join(root, 'manifest.yaml'), `name: fixture\nversion: ${i + 2}\n`);
    commitAll(root, `bump ${i}`);
  }

  // ---- nested repo, two levels down ------------------------------------
  const nested = path.join(root, 'services', 'inner');
  initRepo(nested);
  write(path.join(nested, 'main.py'), 'def main():\n    pass\n');
  commitAll(nested, 'inner initial');
  write(path.join(nested, 'main.py'), 'def main():\n    return 1\n');
  commitAll(nested, 'inner second');
});

afterAll(() => {
  fs.rmSync(root, { recursive: true, force: true });
});

describe('criterion 1 — nested repos are found', () => {
  it('reports each repo with its own commit count and HEAD', () => {
    const inv = inventory(root);
    const roots = inv.repos.map((r) => r.root).sort();
    expect(roots).toEqual(['', 'services/inner']);

    const outer = inv.repos.find((r) => r.root === '')!;
    const inner = inv.repos.find((r) => r.root === 'services/inner')!;

    expect(outer.commitCount).toBe(10);
    expect(inner.commitCount).toBe(2);
    expect(outer.head).toMatch(/^[0-9a-f]{40}$/);
    expect(inner.head).toMatch(/^[0-9a-f]{40}$/);
    expect(outer.head).not.toBe(inner.head);
  });

  it('assigns each file to its nearest enclosing repo', () => {
    const inv = inventory(root);
    const innerFile = inv.files.find((f) => f.path === 'services/inner/main.py')!;
    const outerFile = inv.files.find((f) => f.path === 'src/core.py')!;
    expect(innerFile.repo).toBe('services/inner');
    expect(outerFile.repo).toBe('');
  });
});

describe('criterion 2 — classification is honest', () => {
  it('classifies each fixture the way a human would', () => {
    const inv = inventory(root);
    const at = (p: string) => inv.files.find((f) => f.path === p)!;

    expect(at('package-lock.json').classification).toBe('lockfile');
    expect(at('vendor/leftpad/index.js').classification).toBe('vendored');
    expect(at('dist/bundle.js').classification).toBe('generated');
    expect(at('src/schema_pb2.py').classification).toBe('generated');
    expect(at('src/marked.py').classification).toBe('generated');
    expect(at('tests/test_core.py').classification).toBe('test');
    expect(at('manifest.yaml').classification).toBe('structural');
    expect(at('src/core.py').classification).toBe('source');
    expect(at('reports/bench_dump.json').classification).toBe('generated');
  });

  it('does not call a document in specs/ a test', () => {
    const inv = inventory(root);
    expect(inv.files.find((f) => f.path === 'specs/design.md')!.classification).toBe('data');
  });

  it('records the signal that produced every classification', () => {
    const inv = inventory(root);
    for (const f of inv.files) expect(f.signals.length).toBeGreaterThan(0);
    expect(inv.files.find((f) => f.path === 'src/marked.py')!.signals).toContain('generated-header');
  });
});

describe('criterion 4 — extraction is exact', () => {
  it('matches a hand-written expectation for python', async () => {
    const inv = inventory(root);
    const { extracts } = await extract(root, inv.files);
    const core = extracts.find((e) => e.path === 'src/core.py')!;

    expect(core.parseErrors).toBe(0);
    expect(core.symbols).toEqual([
      { name: 'MAX_RETRIES', kind: 'variable', line: 4, endLine: 4, exported: true },
      { name: 'run', kind: 'function', line: 8, endLine: 9, exported: true },
      { name: '_internal', kind: 'function', line: 12, endLine: 13, exported: false },
      { name: 'Engine', kind: 'class', line: 16, endLine: 21, exported: true },
      { name: 'start', kind: 'method', line: 17, endLine: 18, exported: true },
      { name: '_stop', kind: 'method', line: 20, endLine: 21, exported: false },
    ]);

    expect(core.imports.map((i) => [i.raw, i.resolved])).toEqual([
      ['os', null],
      ['.helpers', 'src/helpers.py'],
    ]);
  });

  it('matches a hand-written expectation for typescript', async () => {
    const inv = inventory(root);
    const { extracts } = await extract(root, inv.files);
    const app = extracts.find((e) => e.path === 'src/app.ts')!;

    expect(app.parseErrors).toBe(0);
    expect(app.symbols).toEqual([
      { name: 'Options', kind: 'interface', line: 4, endLine: 4, exported: true },
      { name: 'Name', kind: 'type', line: 5, endLine: 5, exported: true },
      { name: 'greet', kind: 'function', line: 7, endLine: 9, exported: true },
      { name: 'VERSION', kind: 'variable', line: 11, endLine: 11, exported: true },
      { name: 'Server', kind: 'class', line: 13, endLine: 16, exported: true },
      { name: 'listen', kind: 'method', line: 14, endLine: 14, exported: true },
      { name: '_private', kind: 'method', line: 15, endLine: 15, exported: false },
      { name: 'notExported', kind: 'function', line: 18, endLine: 18, exported: false },
    ]);

    // `./util.js` on the wire is `./util.ts` on disk; `express` leaves the tree.
    expect(app.imports.map((i) => [i.raw, i.resolved])).toEqual([
      ['./util.js', 'src/util.ts'],
      ['express', null],
    ]);
  });

  it('invents nothing — every symbol name appears in the source text', async () => {
    const inv = inventory(root);
    const { extracts } = await extract(root, inv.files);
    for (const ex of extracts) {
      const text = fs.readFileSync(path.join(root, ex.path), 'utf8');
      for (const sym of ex.symbols) expect(text).toContain(sym.name);
    }
  });

  it('counts in-degree from resolved edges only', async () => {
    const inv = inventory(root);
    const { graph } = await extract(root, inv.files);
    // core.py, alpha.py and beta.py all import helpers.py
    expect(graph.inDegree['src/helpers.py']).toBe(3);
    expect(graph.coverage.leftTheTree).toBeGreaterThan(0);
  });
});

describe('criterion 3 — ranking beats length', () => {
  it('ranks the small high-churn structural file above the huge data dump', async () => {
    const inv = inventory(root);
    const { graph } = await extract(root, inv.files);
    const { ranked } = rank(root, inv.files, inv.repos, graph);

    const order = ranked.map((r) => r.path);
    const manifestAt = order.indexOf('manifest.yaml');
    const dumpAt = order.indexOf('reports/bench_dump.json');

    const manifest = ranked[manifestAt]!;
    const dump = ranked[dumpAt]!;

    // The premise of the test: the dump really is far bigger, and really is untouched.
    expect(dump.loc).toBeGreaterThan(manifest.loc * 100);
    expect(manifest.churn).toBeGreaterThan(dump.churn);

    expect(manifestAt).toBeLessThan(dumpAt);
    expect(manifest.score).toBeGreaterThan(dump.score);
  });

  it('floors generated, vendored and lockfile content to zero', async () => {
    const inv = inventory(root);
    const { graph } = await extract(root, inv.files);
    const { ranked } = rank(root, inv.files, inv.repos, graph);
    const at = (p: string) => ranked.find((r) => r.path === p)!;

    expect(at('package-lock.json').score).toBe(0);
    expect(at('vendor/leftpad/index.js').score).toBe(0);
    expect(at('dist/bundle.js').score).toBe(0);
  });

  it('counts churn in the file’s own repo, not the parent’s', async () => {
    const inv = inventory(root);
    const { graph } = await extract(root, inv.files);
    const { ranked } = rank(root, inv.files, inv.repos, graph);
    // The outer repo cannot see this file at all; only the nested repo's log has it.
    expect(ranked.find((r) => r.path === 'services/inner/main.py')!.churn).toBe(2);
  });
});

describe('criterion 6 — content-hash keying', () => {
  it('gives an unchanged file the same key across two runs, and a changed file a new one', async () => {
    const before = inventory(root).files.find((f) => f.path === 'src/helpers.py')!;
    const stableBefore = inventory(root).files.find((f) => f.path === 'src/core.py')!;

    write(path.join(root, 'src/helpers.py'), 'def shout(s):\n    return str(s).upper() + "!"\n');
    commitAll(root, 'edit helpers');

    const after = inventory(root).files.find((f) => f.path === 'src/helpers.py')!;
    const stableAfter = inventory(root).files.find((f) => f.path === 'src/core.py')!;

    expect(after.sha256).not.toBe(before.sha256);
    expect(stableAfter.sha256).toBe(stableBefore.sha256);
  });
});

describe('criterion 7 — cost is reported, not hidden', () => {
  it('reports token spend explicitly even when it is zero', async () => {
    const { manifest } = await digest(root, { write: false });
    expect(manifest.cost.tokens).toEqual({ fast: 0, strong: 0 });
    expect(manifest.cost.filesInterpreted).toBe(0);
    expect(manifest.cost.filesScanned).toBeGreaterThan(0);
    expect(manifest.cost.wallMs).toBeGreaterThanOrEqual(0);
    expect(manifest.stagesNotBuilt).toContain('4-interpret');
  });

  it('states the import graph’s own coverage', async () => {
    const { manifest } = await digest(root, { write: false });
    expect(manifest.graphCoverage.totalImports).toBeGreaterThan(0);
    expect(manifest.graphCoverage.note).toMatch(/not the structure/);
  });
});
