/**
 * Acceptance criteria 1-4 and 6, against fixtures built on the fly.
 *
 * Every fixture is a real git repository with real commits, because the signals under
 * test (nested-repo discovery, churn) do not exist without one.
 */

import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';

import { inventory } from '../src/inventory.js';
import { extract } from '../src/extract.js';
import { rank } from '../src/rank.js';
import { digest } from '../src/digest.js';
import { renderView } from '../src/view.js';
import { rollup } from '../src/rollup.js';
import { planIncremental } from '../src/incremental.js';
import { buildTourSteps } from '../src/tour.js';
import { buildCodeTour, buildArchitectureSteps } from '../src/codetour.js';
import { buildArchitecture } from '../src/architecture.js';
import { renderRepoView } from '../src/repoview.js';
import { fingerprint } from '../src/server.js';

let root: string;

function git(cwd: string, ...args: string[]): void {
  execFileSync('git', ['-C', cwd, ...args], { stdio: ['ignore', 'ignore', 'ignore'] });
}

function initRepo(dir: string): void {
  fs.mkdirSync(dir, { recursive: true });
  git(dir, 'init', '-q');
  git(dir, 'config', 'user.email', 'fixture@test.local');
  git(dir, 'config', 'user.name', 'fixture');
}

function write(file: string, body: string): void {
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, body);
}

function commitAll(dir: string, message: string): void {
  git(dir, 'add', '-A');
  git(dir, 'commit', '-q', '-m', message, '--allow-empty');
}

beforeAll(() => {
  root = fs.mkdtempSync(path.join(os.tmpdir(), 'repo-tour-fixture-'));

  // ---- outer repo -------------------------------------------------------
  initRepo(root);

  // A small, high-churn structural file. This is the `manifest.yaml` shape.
  write(path.join(root, 'manifest.yaml'), 'name: fixture\nversion: 1\n');

  // A huge, single-commit data file with no importers. This is the benchmark-exhaust shape.
  write(
    path.join(root, 'reports/bench_dump.json'),
    JSON.stringify({ rows: Array.from({ length: 4000 }, (_, i) => ({ i, v: i * 2 })) }, null, 2),
  );

  write(
    path.join(root, 'src/core.py'),
    [
      'import os',
      'from .helpers import shout',
      '',
      'MAX_RETRIES = 3',
      '_PRIVATE = 1',
      '',
      '',
      'def run(job):',
      '    """Send a job through the shouter.',
      '',
      '    Args: job — the thing to shout.',
      '    """',
      '    return shout(job)',
      '',
      '',
      'def _internal():',
      '    pass',
      '',
      '',
      'class Engine:',
      '    def start(self):',
      '        pass',
      '',
      '    def _stop(self):',
      '        pass',
      '',
    ].join('\n'),
  );

  write(
    path.join(root, 'src/helpers.py'),
    ['def shout(s):', '    return str(s).upper()', ''].join('\n'),
  );

  // Two more importers of helpers.py, so in-degree is a real number.
  write(path.join(root, 'src/alpha.py'), 'from .helpers import shout\n');
  write(path.join(root, 'src/beta.py'), 'from src.helpers import shout\n');

  write(
    path.join(root, 'src/app.ts'),
    [
      "import { shout } from './util.js';",
      "import express from 'express';",
      '',
      'export interface Options { loud: boolean }',
      'export type Name = string;',
      '',
      'export function greet(n: Name): string {',
      '  return shout(n);',
      '}',
      '',
      'export const VERSION = 2;',
      '',
      'export class Server {',
      '  listen() {}',
      '  _private() {}',
      '}',
      '',
      'function notExported() {}',
      '',
    ].join('\n'),
  );

  write(path.join(root, 'src/util.ts'), 'export function shout(s: string) { return s.toUpperCase(); }\n');

  // Things that must be floored to zero (criterion 2).
  write(path.join(root, 'package-lock.json'), '{"lockfileVersion": 3}\n');
  write(path.join(root, 'vendor/leftpad/index.js'), 'module.exports = function () {};\n');
  write(path.join(root, 'dist/bundle.js'), 'console.log(1);\n');
  write(path.join(root, 'src/schema_pb2.py'), 'DESCRIPTOR = None\n');
  write(path.join(root, 'src/marked.py'), '# @generated by a tool\nX = 1\n');

  // A document that lives in a `specs/` folder and is NOT a test.
  write(path.join(root, 'specs/design.md'), '# Design\n\nProse, not a test.\n');

  // A real test file.
  write(path.join(root, 'tests/test_core.py'), 'def test_run():\n    assert True\n');

  commitAll(root, 'initial');

  // Churn: touch manifest.yaml many times, the dump never again.
  for (let i = 0; i < 9; i++) {
    write(path.join(root, 'manifest.yaml'), `name: fixture\nversion: ${i + 2}\n`);
    commitAll(root, `bump ${i}`);
  }

  // ---- nested repo, two levels down ------------------------------------
  const nested = path.join(root, 'services', 'inner');
  initRepo(nested);
  write(path.join(nested, 'main.py'), 'def main():\n    pass\n');
  commitAll(nested, 'inner initial');
  write(path.join(nested, 'main.py'), 'def main():\n    return 1\n');
  commitAll(nested, 'inner second');
});

afterAll(() => {
  fs.rmSync(root, { recursive: true, force: true });
});

describe('criterion 1 — nested repos are found', () => {
  it('reports each repo with its own commit count and HEAD', () => {
    const inv = inventory(root);
    const roots = inv.repos.map((r) => r.root).sort();
    expect(roots).toEqual(['', 'services/inner']);

    const outer = inv.repos.find((r) => r.root === '')!;
    const inner = inv.repos.find((r) => r.root === 'services/inner')!;

    expect(outer.commitCount).toBe(10);
    expect(inner.commitCount).toBe(2);
    expect(outer.head).toMatch(/^[0-9a-f]{40}$/);
    expect(inner.head).toMatch(/^[0-9a-f]{40}$/);
    expect(outer.head).not.toBe(inner.head);
  });

  it('assigns each file to its nearest enclosing repo', () => {
    const inv = inventory(root);
    const innerFile = inv.files.find((f) => f.path === 'services/inner/main.py')!;
    const outerFile = inv.files.find((f) => f.path === 'src/core.py')!;
    expect(innerFile.repo).toBe('services/inner');
    expect(outerFile.repo).toBe('');
  });
});

describe('criterion 2 — classification is honest', () => {
  it('classifies each fixture the way a human would', () => {
    const inv = inventory(root);
    const at = (p: string) => inv.files.find((f) => f.path === p)!;

    expect(at('package-lock.json').classification).toBe('lockfile');
    expect(at('vendor/leftpad/index.js').classification).toBe('vendored');
    expect(at('dist/bundle.js').classification).toBe('generated');
    expect(at('src/schema_pb2.py').classification).toBe('generated');
    expect(at('src/marked.py').classification).toBe('generated');
    expect(at('tests/test_core.py').classification).toBe('test');
    expect(at('manifest.yaml').classification).toBe('structural');
    expect(at('src/core.py').classification).toBe('source');
    expect(at('reports/bench_dump.json').classification).toBe('generated');
  });

  it('does not call a document in specs/ a test', () => {
    const inv = inventory(root);
    expect(inv.files.find((f) => f.path === 'specs/design.md')!.classification).toBe('data');
  });

  it('records the signal that produced every classification', () => {
    const inv = inventory(root);
    for (const f of inv.files) expect(f.signals.length).toBeGreaterThan(0);
    expect(inv.files.find((f) => f.path === 'src/marked.py')!.signals).toContain('generated-header');
  });
});

describe('criterion 4 — extraction is exact', () => {
  it('matches a hand-written expectation for python', async () => {
    const inv = inventory(root);
    const { extracts } = await extract(root, inv.files);
    const core = extracts.find((e) => e.path === 'src/core.py')!;

    expect(core.parseErrors).toBe(0);
    expect(core.symbols).toEqual([
      { name: 'MAX_RETRIES', kind: 'variable', line: 4, endLine: 4, exported: true, doc: null },
      // The docstring is read, and the `Args:` section is cut — a tour wants the sentence,
      // not the parameter table.
      { name: 'run', kind: 'function', line: 8, endLine: 13, exported: true,
        doc: 'Send a job through the shouter.' },
      { name: '_internal', kind: 'function', line: 16, endLine: 17, exported: false, doc: null },
      { name: 'Engine', kind: 'class', line: 20, endLine: 25, exported: true, doc: null },
      { name: 'start', kind: 'method', line: 21, endLine: 22, exported: true, doc: null },
      { name: '_stop', kind: 'method', line: 24, endLine: 25, exported: false, doc: null },
    ]);

    expect(core.imports.map((i) => [i.raw, i.resolved])).toEqual([
      ['os', null],
      ['.helpers', 'src/helpers.py'],
    ]);
  });

  it('matches a hand-written expectation for typescript', async () => {
    const inv = inventory(root);
    const { extracts } = await extract(root, inv.files);
    const app = extracts.find((e) => e.path === 'src/app.ts')!;

    expect(app.parseErrors).toBe(0);
    expect(app.symbols).toEqual([
      { name: 'Options', kind: 'interface', line: 4, endLine: 4, exported: true, doc: null },
      { name: 'Name', kind: 'type', line: 5, endLine: 5, exported: true, doc: null },
      { name: 'greet', kind: 'function', line: 7, endLine: 9, exported: true, doc: null },
      { name: 'VERSION', kind: 'variable', line: 11, endLine: 11, exported: true, doc: null },
      { name: 'Server', kind: 'class', line: 13, endLine: 16, exported: true, doc: null },
      { name: 'listen', kind: 'method', line: 14, endLine: 14, exported: true, doc: null },
      { name: '_private', kind: 'method', line: 15, endLine: 15, exported: false, doc: null },
      { name: 'notExported', kind: 'function', line: 18, endLine: 18, exported: false, doc: null },
    ]);

    // `./util.js` on the wire is `./util.ts` on disk; `express` leaves the tree.
    expect(app.imports.map((i) => [i.raw, i.resolved])).toEqual([
      ['./util.js', 'src/util.ts'],
      ['express', null],
    ]);
  });

  it('invents nothing — every symbol name appears in the source text', async () => {
    const inv = inventory(root);
    const { extracts } = await extract(root, inv.files);
    for (const ex of extracts) {
      const text = fs.readFileSync(path.join(root, ex.path), 'utf8');
      for (const sym of ex.symbols) expect(text).toContain(sym.name);
    }
  });

  it('counts in-degree from resolved edges only', async () => {
    const inv = inventory(root);
    const { graph } = await extract(root, inv.files);
    // core.py, alpha.py and beta.py all import helpers.py
    expect(graph.inDegree['src/helpers.py']).toBe(3);
    expect(graph.coverage.leftTheTree).toBeGreaterThan(0);
  });
});

describe('criterion 3 — ranking beats length', () => {
  it('ranks the small high-churn structural file above the huge data dump', async () => {
    const inv = inventory(root);
    const { graph } = await extract(root, inv.files);
    const { ranked } = rank(root, inv.files, inv.repos, graph);

    const order = ranked.map((r) => r.path);
    const manifestAt = order.indexOf('manifest.yaml');
    const dumpAt = order.indexOf('reports/bench_dump.json');

    const manifest = ranked[manifestAt]!;
    const dump = ranked[dumpAt]!;

    // The premise of the test: the dump really is far bigger, and really is untouched.
    expect(dump.loc).toBeGreaterThan(manifest.loc * 100);
    expect(manifest.churn).toBeGreaterThan(dump.churn);

    expect(manifestAt).toBeLessThan(dumpAt);
    expect(manifest.score).toBeGreaterThan(dump.score);
  });

  it('floors generated, vendored and lockfile content to zero', async () => {
    const inv = inventory(root);
    const { graph } = await extract(root, inv.files);
    const { ranked } = rank(root, inv.files, inv.repos, graph);
    const at = (p: string) => ranked.find((r) => r.path === p)!;

    expect(at('package-lock.json').score).toBe(0);
    expect(at('vendor/leftpad/index.js').score).toBe(0);
    expect(at('dist/bundle.js').score).toBe(0);
  });

  it('counts churn in the file’s own repo, not the parent’s', async () => {
    const inv = inventory(root);
    const { graph } = await extract(root, inv.files);
    const { ranked } = rank(root, inv.files, inv.repos, graph);
    // The outer repo cannot see this file at all; only the nested repo's log has it.
    expect(ranked.find((r) => r.path === 'services/inner/main.py')!.churn).toBe(2);
  });
});

describe('criterion 6 — content-hash keying', () => {
  it('gives an unchanged file the same key across two runs, and a changed file a new one', async () => {
    const before = inventory(root).files.find((f) => f.path === 'src/helpers.py')!;
    const stableBefore = inventory(root).files.find((f) => f.path === 'src/core.py')!;

    write(path.join(root, 'src/helpers.py'), 'def shout(s):\n    return str(s).upper() + "!"\n');
    commitAll(root, 'edit helpers');

    const after = inventory(root).files.find((f) => f.path === 'src/helpers.py')!;
    const stableAfter = inventory(root).files.find((f) => f.path === 'src/core.py')!;

    expect(after.sha256).not.toBe(before.sha256);
    expect(stableAfter.sha256).toBe(stableBefore.sha256);
  });
});

describe('criterion 7 — cost is reported, not hidden', () => {
  it('reports token spend explicitly even when it is zero', async () => {
    const { manifest } = await digest(root, { write: false });
    expect(manifest.cost.tokens).toEqual({ fast: 0, strong: 0 });
    expect(manifest.cost.filesInterpreted).toBe(0);
    expect(manifest.cost.filesScanned).toBeGreaterThan(0);
    expect(manifest.cost.wallMs).toBeGreaterThanOrEqual(0);
    expect(manifest.stagesNotBuilt).toContain('4-interpret');
  });

  it('states the import graph’s own coverage', async () => {
    const { manifest } = await digest(root, { write: false });
    expect(manifest.graphCoverage.totalImports).toBeGreaterThan(0);
    expect(manifest.graphCoverage.note).toMatch(/not the structure/);
  });
});

describe('criterion 8 — inspectable by a human', () => {
  it('renders a genuinely self-contained page: no external requests at all', async () => {
    const result = await digest(root, { write: false });
    const html = renderView(result);

    // Any absolute URL means the page needs the network to render correctly.
    const external = html.match(/(?:https?:)?\/\/[a-zA-Z0-9.-]+/g) ?? [];
    expect(external).toEqual([]);
    expect(html).not.toMatch(/<link[^>]+href=/i);
    expect(html).not.toMatch(/<script[^>]+src=/i);
    expect(html).not.toMatch(/fetch\(|XMLHttpRequest|WebSocket/);
  });

  it('says out loud that the digest is partial rather than implying completeness', async () => {
    const result = await digest(root, { write: false });
    const html = renderView(result);
    expect(html).toMatch(/Nothing on this page was written by a model/);
    expect(html).toMatch(/4-interpret — not built/);
    expect(html).toMatch(/not the structure/);
  });

  it('never truncates silently — a capped table says what it dropped', async () => {
    const result = await digest(root, { write: false });
    const capped = renderView(result, { maxRows: 3 });
    const dropped = result.ranked.length - 3;
    expect(capped).toMatch(/rows are not[\s\S]*?embedded/);
    expect(capped).toContain(dropped.toLocaleString());
  });

  it('embeds every ranked row with the components that produced its score', async () => {
    const result = await digest(root, { write: false });
    const html = renderView(result);
    const payload = /window\.__DIGEST__ = (\{[\s\S]*?\});/.exec(html);
    expect(payload).not.toBeNull();
    const data = JSON.parse(payload![1]!) as { rows: Array<Record<string, unknown>> };
    expect(data.rows.length).toBeGreaterThan(0);
    for (const row of data.rows) {
      expect(row).toHaveProperty('components');
      expect(row).toHaveProperty('signals');
      expect(row).toHaveProperty('symbols');
    }
  });
});

describe('criterion 5 — the rollup holds', () => {
  it('gives every directory, subsystem and repo a digest built from its children', async () => {
    const r = await digest(root, { write: false });
    const paths = new Set(r.tiers.map((t) => t.path));

    expect(paths.has('')).toBe(true);
    expect(paths.has('src')).toBe(true);
    expect(paths.has('services')).toBe(true);
    expect(paths.has('services/inner')).toBe(true);

    // A repo root is a 'repo'; a directory directly under one is a 'subsystem'.
    expect(r.tiers.find((t) => t.path === '')!.kind).toBe('repo');
    expect(r.tiers.find((t) => t.path === 'services/inner')!.kind).toBe('repo');
    expect(r.tiers.find((t) => t.path === 'src')!.kind).toBe('subsystem');

    // Every tier declares, in its own data, that it was built from children.
    for (const t of r.tiers) expect(t.sourcedFrom).toBe('children');
  });

  it('rolls counts upward: a parent equals the sum of its children', async () => {
    const r = await digest(root, { write: false });
    const byPath = new Map(r.tiers.map((t) => [t.path, t] as const));
    const rootTier = byPath.get('')!;

    const sumOfChildren =
      rootTier.childTiers.reduce((n, c) => n + byPath.get(c)!.fileCount, 0) +
      rootTier.childFiles.length;
    expect(rootTier.fileCount).toBe(sumOfChildren);
    expect(rootTier.fileCount).toBe(r.inventory.files.length);
  });

  it('hashes a tier from its children only, so a tier is stale iff a child is', async () => {
    const before = await digest(root, { write: false });
    const beforeByPath = new Map(before.tiers.map((t) => [t.path, t.hash] as const));

    write(path.join(root, 'src/helpers.py'), 'def shout(s):\n    return str(s).upper() + "?"\n');
    commitAll(root, 'edit helpers again');

    const after = await digest(root, { write: false });
    const afterByPath = new Map(after.tiers.map((t) => [t.path, t.hash] as const));

    // src changed, so src and the root are stale...
    expect(afterByPath.get('src')).not.toBe(beforeByPath.get('src'));
    expect(afterByPath.get('')).not.toBe(beforeByPath.get(''));
    // ...but an untouched sibling subtree is byte-identical and can be reused.
    expect(afterByPath.get('services/inner')).toBe(beforeByPath.get('services/inner'));
  });
});

describe('criterion 6 — incremental works', () => {
  it('reuses unchanged files and reports the count', async () => {
    const first = await digest(root, { write: false });
    const prior = first.inventory.files.map((f) => ({ path: f.path, sha256: f.sha256 }));

    write(path.join(root, 'src/core.py'), 'import os\n\n\ndef run(job):\n    return job\n');
    commitAll(root, 'rewrite core');
    const second = await digest(root, { write: false });

    const plan = planIncremental(prior, second.inventory.files, second.tiers);
    expect(plan.counts.recomputed).toBe(1);
    expect(plan.recompute).toEqual(['src/core.py']);
    expect(plan.counts.reused).toBe(plan.counts.total - 1);
    expect(plan.counts.reusePercent).toBeGreaterThan(90);
  });

  it('carries a renamed file across for free instead of recomputing it', async () => {
    const first = await digest(root, { write: false });
    const prior = first.inventory.files.map((f) => ({ path: f.path, sha256: f.sha256 }));

    fs.renameSync(path.join(root, 'src/alpha.py'), path.join(root, 'src/renamed_alpha.py'));
    commitAll(root, 'rename alpha');
    const second = await digest(root, { write: false });

    const plan = planIncremental(prior, second.inventory.files, second.tiers);
    expect(plan.carried).toEqual([
      { from: 'src/alpha.py', to: 'src/renamed_alpha.py', sha256: expect.any(String) },
    ]);
    expect(plan.recompute).toEqual([]);
    expect(plan.deleted).toEqual([]);
  });

  it('does not digest its own cache — a second run with no edits reuses everything', async () => {
    // Found by running the tool twice on its own repo: run 1 writes .repo-tour/, and
    // run 2 then inventoried ~100 cache files as brand-new additions.
    const cache = path.join(root, '.repo-tour');
    fs.rmSync(cache, { recursive: true, force: true });

    const first = await digest(root, { write: true });
    expect(fs.existsSync(cache)).toBe(true);

    const second = await digest(root, { write: true });
    expect(second.inventory.files.length).toBe(first.inventory.files.length);
    expect(second.inventory.files.some((f) => f.path.startsWith('.repo-tour/'))).toBe(false);
    expect(second.plan).not.toBeNull();
    expect(second.plan!.counts.added).toBe(0);
    expect(second.plan!.counts.recomputed).toBe(0);
    expect(second.plan!.counts.reusePercent).toBe(100);

    fs.rmSync(cache, { recursive: true, force: true });
  });

  it('drops a deleted file and marks its ancestors stale', async () => {
    const first = await digest(root, { write: false });
    const prior = first.inventory.files.map((f) => ({ path: f.path, sha256: f.sha256 }));

    fs.rmSync(path.join(root, 'src/beta.py'));
    commitAll(root, 'delete beta');
    const second = await digest(root, { write: false });

    const plan = planIncremental(prior, second.inventory.files, second.tiers);
    expect(plan.deleted).toEqual(['src/beta.py']);
    expect(plan.invalidatedTiers).toContain('src');
    expect(plan.invalidatedTiers).toContain('');
    expect(plan.invalidatedTiers).not.toContain('services/inner');
  });
});

describe('the tour is a projection of the digest, not a separate artifact', () => {
  it('generates steps whose claims are backed by digest numbers', async () => {
    const r = await digest(root, { write: false });
    const steps = buildTourSteps(r);

    expect(steps.length).toBeGreaterThan(3);
    for (const s of steps) {
      expect(s.target).toBeTruthy();
      expect(s.text.length).toBeGreaterThan(20);
    }
    // The opening step states the real file count.
    expect(steps[0]!.text).toContain(r.inventory.files.length.toLocaleString());
    // Any step pointing at a file row points at a file that actually exists.
    for (const s of steps) {
      if (!s.filterTo) continue;
      expect(r.ranked.some((x) => x.path === s.filterTo)).toBe(true);
    }
  });

  it('inlines the tour engine with no external requests', async () => {
    const r = await digest(root, { write: false });
    const html = renderView(r, { tour: buildTourSteps(r) });
    expect(html).toMatch(/window\.__TOUR__/);
    expect(html).toMatch(/Tour\.start/);
    expect((html.match(/(?:https?:)?\/\/[a-zA-Z0-9.-]+/g) ?? [])).toEqual([]);
    expect(html).not.toMatch(/<script[^>]+src=/i);
  });
});

describe('the tour walks CODE, not metrics', () => {
  it('anchors every step to a real file and a real line range', async () => {
    const r = await digest(root, { write: false });
    const plan = buildCodeTour(r);

    expect(plan.steps.length).toBeGreaterThan(2);
    const byPath = new Map(r.inventory.files.map((f) => [f.path, f] as const));

    for (const s of plan.steps) {
      const f = byPath.get(s.file);
      expect(f, `step points at a file that is not in the tree: ${s.file}`).toBeDefined();
      expect(s.startLine).toBeGreaterThanOrEqual(1);
      expect(s.endLine).toBeGreaterThanOrEqual(s.startLine);
      // never point past the end of the file
      expect(s.endLine).toBeLessThanOrEqual(f!.loc + 1);
      expect(plan.itinerary).toContain(s.file);
    }
  });

  it('quotes the author when the author left a docstring', async () => {
    // Its own tree: the shared fixture is mutated by the incremental tests above, and a
    // test that depends on their leftovers is a test that fails for the wrong reason.
    const own = fs.mkdtempSync(path.join(os.tmpdir(), 'repo-tour-doc-'));
    try {
      initRepo(own);
      write(
        path.join(own, 'pipeline.py'),
        [
          'def run(job):',
          '    """Send a job through the shouter.',
          '',
          '    Args: job — ignored here.',
          '    """',
          '    return job',
          '',
        ].join('\n'),
      );
      commitAll(own, 'add pipeline');

      const r = await digest(own, { write: false });
      const plan = buildCodeTour(r);
      const quoted = plan.steps.filter((s) => s.text.includes('The author says'));

      expect(quoted.length).toBeGreaterThan(0);
      // the sentence is kept, the Args: section is cut
      expect(quoted[0]!.text).toContain('Send a job through the shouter.');
      expect(quoted[0]!.text).not.toContain('Args:');
    } finally {
      fs.rmSync(own, { recursive: true, force: true });
    }
  });

  it('closes with an honest account of what it did and did not cover', async () => {
    const r = await digest(root, { write: false });
    const plan = buildCodeTour(r);
    const last = plan.steps[plan.steps.length - 1]!;

    // It names the coverage rather than implying the tour was the whole repo...
    expect(last.text).toContain(r.inventory.files.length.toLocaleString());
    expect(last.text).toMatch(/did not hide the rest/);
    // ...and it is the tour talking about itself, so stage 4 must leave it alone.
    expect(last.synthetic).toBe(true);
  });

  it('spreads its stops instead of drowning in the top-ranked file', async () => {
    const r = await digest(root, { write: false });
    const plan = buildCodeTour(r);
    const perFile = new Map<string, number>();
    for (const s of plan.steps) perFile.set(s.file, (perFile.get(s.file) ?? 0) + 1);

    // No single file may take more than a third of the tour. app.py once took 7 of 14.
    const worst = Math.max(...perFile.values());
    expect(worst).toBeLessThanOrEqual(Math.ceil(plan.steps.length / 3));
    // And no file on the itinerary gets a lone "here is a file" nod.
    for (const f of plan.itinerary) expect(perFile.get(f) ?? 0).toBeGreaterThanOrEqual(2);
  });

  it('renders a self-contained repo page with the code actually in it', async () => {
    const r = await digest(root, { write: false });
    const plan = buildCodeTour(r);
    const html = renderRepoView(r, { steps: plan.steps, itinerary: plan.itinerary });

    // the real source text is embedded, not just its metrics
    expect(html).toContain('def run(job)');
    expect(html).toMatch(/window\.__STEPS__/);
    // The tour must never start on its own — it waits for the button.
    expect(html).toMatch(/id="start"/);
    expect(html).toMatch(/btn\.addEventListener\('click', start\)/);
    expect(html).not.toMatch(/start\(\);\s*\}\)\(\);/);
    // The guide is a docked panel, not a floating coachmark bubble.
    expect(html).toMatch(/id="guide"/);
    expect(html).not.toMatch(/tour-bubble/);
    expect((html.match(/(?:https?:)?\/\/[a-zA-Z0-9.-]+/g) ?? [])).toEqual([]);
    expect(html).not.toMatch(/<script[^>]+src=/i);
    // and the scoring rubric is NOT on the screen
    expect(html).not.toMatch(/in-degree|churn 0\.45/);
  });
});

describe('the notes panel carries provenance', () => {
  it('ships a notes pane, an anchor, and export controls', async () => {
    const r = await digest(root, { write: false });
    const plan = buildCodeTour(r);
    const html = renderRepoView(r, { steps: plan.steps, itinerary: plan.itinerary });

    for (const id of ['tab-notes', 'a-what', 'ntext', 'nsave', 'nlist', 'ncopy', 'ndl', 'gnote']) {
      expect(html, `missing #${id}`).toContain(`id="${id}"`);
    }
    // A note taken during the tour must record which stop prompted it.
    expect(html).toMatch(/anchorFromStop/);
    expect(html).toMatch(/stopIndex/);
    expect(html).toMatch(/prompted by tour stop/);
  });

  it('keeps notes across commits but stamps the one they were taken at', async () => {
    const r = await digest(root, { write: false });
    const plan = buildCodeTour(r);
    const html = renderRepoView(r, { steps: plan.steps, itinerary: plan.itinerary });

    // Notes are review material: a new tour must not throw them away...
    expect(html).toMatch(/repotour:notes:' \+ repo\.name/);
    // ...but a note taken against code that has since moved must say so, not sit there
    // looking as though it still applies.
    expect(html).toMatch(/head: repo\.head/);
    expect(html).toMatch(/code has moved/);
    const head = r.manifest.repos.find((x) => x.root === '')?.head;
    expect(html).toContain(head!);
  });

  it('says on the page that it is a snapshot of one commit', async () => {
    const r = await digest(root, { write: false });
    const plan = buildCodeTour(r);
    const html = renderRepoView(r, { steps: plan.steps, itinerary: plan.itinerary });

    // A static page cannot know it has gone stale, so it must at least be honest about
    // being static — refreshing it will never pick up new code.
    expect(html).toMatch(/A snapshot of/);
    // It must be clear that a file cannot gain FEATURES either, not just code — that was
    // the actual confusion: refreshing an old export and wondering where chapters were.
    expect(html).toMatch(/new chapters/);
    expect(html).toMatch(/start\.sh/);
  });

  it('every piece of client script is valid JavaScript', async () => {
    // A stray escape inside a template literal once emitted `/\r?\n/` as a real newline
    // inside a regex, which killed the whole app script and left an empty file tree. The
    // page renders fine and does nothing, so only parsing it catches this.
    const r = await digest(root, { write: false });
    const plan = buildCodeTour(r);
    const html = renderRepoView(r, { steps: plan.steps, itinerary: plan.itinerary });

    const blocks = [...html.matchAll(/<script>([\s\S]*?)<\/script>/g)].map((m) => m[1]!);
    expect(blocks.length).toBeGreaterThan(3);
    for (const [i, code] of blocks.entries()) {
      expect(() => new Function(code), `script block ${i} does not parse`).not.toThrow();
    }
  });
});

describe('the app refreshes on real change, not on its own output', () => {
  it('ignores its own .repo-tour cache when deciding the repo has moved', async () => {
    // The digest writes its cache INTO the repo, so `git status` reports it. Fingerprinting
    // that would make every build look like a change, leaving the page permanently "stale"
    // and rebuilding forever — which is exactly what happened the first time.
    const before = fingerprint(root);

    await digest(root, { write: true });
    const afterCacheWritten = fingerprint(root);
    expect(afterCacheWritten, 'writing the cache must not count as a change').toBe(before);

    // A real edit must still be seen.
    write(path.join(root, 'src/newly_added.py'), 'def added():\n    return 1\n');
    const afterRealEdit = fingerprint(root);
    expect(afterRealEdit).not.toBe(before);

    fs.rmSync(path.join(root, 'src/newly_added.py'));
    fs.rmSync(path.join(root, '.repo-tour'), { recursive: true, force: true });
  });
});

describe('the tour is organised in chapters', () => {
  it('gives every stop a chapter, and keeps each chapter contiguous', async () => {
    const r = await digest(root, { write: false });
    const arch = buildArchitecture(r);
    const plan = buildCodeTour(r);
    const steps = [
      ...buildArchitectureSteps(arch, 'fixture', r.inventory.files.length),
      ...plan.steps,
    ];

    for (const s of steps) expect(s.chapter, `no chapter on "${s.title}"`).toBeDefined();

    // A key must never come back after another key has started: chapters are ranges, and
    // a table of contents built from a non-contiguous list would list one twice.
    const seen = new Set<string>();
    let last = '';
    for (const s of steps) {
      const key = s.chapter!.key;
      if (key !== last) {
        expect(seen.has(key), `chapter "${key}" resumes after another`).toBe(false);
        seen.add(key);
        last = key;
      }
    }
  });

  it('makes the system one chapter and each file its own', async () => {
    const r = await digest(root, { write: false });
    const arch = buildArchitecture(r);
    const plan = buildCodeTour(r);

    const archSteps = buildArchitectureSteps(arch, 'fixture', r.inventory.files.length);
    if (archSteps.length) {
      expect(new Set(archSteps.map((s) => s.chapter!.key)).size).toBe(1);
    }
    for (const file of plan.itinerary) {
      const mine = plan.steps.filter((s) => s.file === file && !s.synthetic);
      expect(new Set(mine.map((s) => s.chapter!.key))).toEqual(new Set([file]));
    }
    // The closing stop is its own chapter, not tacked onto the last file's.
    const closing = plan.steps[plan.steps.length - 1]!;
    expect(closing.chapter!.key).toBe('@end');
  });

  it('renders a table of contents you can start from', async () => {
    const r = await digest(root, { write: false });
    const plan = buildCodeTour(r);
    const html = renderRepoView(r, { steps: plan.steps, itinerary: plan.itinerary });

    expect(html).toContain('id="idletoc"');   // pickable before the tour starts
    expect(html).toContain('id="chaphead"');  // and reachable during it
    expect(html).toContain('id="gskip"');     // a chapter can be skipped
    expect(html).toMatch(/Next chapter/);
  });
});

describe('the rendered page is well-formed enough to drive', () => {
  it('has no duplicate element ids', async () => {
    // Moving the tour button into the sticky header left the old one behind, so the page
    // shipped two #start buttons — the second one dead. Every selector in the client
    // script assumes ids are unique; this is cheap to check and impossible to eyeball.
    const r = await digest(root, { write: false });
    const plan = buildCodeTour(r);
    const html = renderRepoView(r, { steps: plan.steps, itinerary: plan.itinerary });

    const ids = [...html.matchAll(/\sid="([^"]+)"/g)].map((m) => m[1]!);
    const seen = new Set<string>();
    const dupes = ids.filter((id) => (seen.has(id) ? true : (seen.add(id), false)));
    expect(dupes, `duplicate ids: ${[...new Set(dupes)].join(', ')}`).toEqual([]);
  });

  it('wires every id the client script reaches for', async () => {
    const r = await digest(root, { write: false });
    const plan = buildCodeTour(r);
    const html = renderRepoView(r, { steps: plan.steps, itinerary: plan.itinerary });

    const wanted = [...html.matchAll(/getElementById\('([^']+)'\)/g)].map((m) => m[1]!);
    for (const id of new Set(wanted)) {
      expect(html.includes(`id="${id}"`), `script reaches for #${id}, which the markup never renders`).toBe(true);
    }
  });
});

describe('the page never scrolls itself', () => {
  it('uses no scrollIntoView anywhere in the client script', async () => {
    // scrollIntoView scrolls EVERY scrollable ancestor, so keeping a file-tree row visible
    // also scrolled the document: the page opened 58px down, with the header bars already
    // hidden under the sticky top bar. The tour button looked buried wherever it was put,
    // because the page had moved rather than the button. Container scrolling only.
    const r = await digest(root, { write: false });
    const plan = buildCodeTour(r);
    const html = renderRepoView(r, { steps: plan.steps, itinerary: plan.itinerary });

    const scripts = [...html.matchAll(/<script>([\s\S]*?)<\/script>/g)].map((m) => m[1]!).join('\n');
    // A CALL, not the word — the comment explaining why we avoid it mentions it by name.
    expect(scripts).not.toMatch(/scrollIntoView\s*\(/);
  });
});
