/**
 * Stage 1 — Inventory. Free, deterministic, exact.
 *
 * Walks the tree, discovers every repository *structurally* (not via `git ls-files`
 * at the root, which is confidently wrong on nested repos), and classifies each file
 * from signals only — never from a model.
 */

import { createHash } from 'node:crypto';
import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import type { Classification, FileRecord, Inventory, RepoRef } from './types.js';

/** Directories never worth descending into. Their *presence* is still recorded as a signal. */
const NEVER_DESCEND = new Set([
  'node_modules', '.venv', 'venv', '__pycache__', '.mypy_cache', '.pytest_cache',
  '.ruff_cache', '.tox', '.next', '.nuxt', '.svelte-kit', '.turbo', '.parcel-cache',
  '.gradle', '.idea', '.vscode-test', 'site-packages', '.terraform',
]);

const LANGUAGE_BY_EXT: Record<string, string> = {
  '.py': 'python', '.pyi': 'python',
  '.js': 'javascript', '.mjs': 'javascript', '.cjs': 'javascript', '.jsx': 'javascript',
  '.ts': 'typescript', '.mts': 'typescript', '.cts': 'typescript',
  '.tsx': 'tsx',
  '.rs': 'rust', '.go': 'go', '.rb': 'ruby', '.java': 'java', '.kt': 'kotlin',
  '.c': 'c', '.h': 'c', '.cc': 'cpp', '.cpp': 'cpp', '.hpp': 'cpp',
  '.sh': 'shell', '.bash': 'shell', '.sql': 'sql',
  '.json': 'json', '.yaml': 'yaml', '.yml': 'yaml', '.toml': 'toml', '.xml': 'xml',
  '.md': 'markdown', '.rst': 'rst', '.txt': 'text',
  '.css': 'css', '.scss': 'css', '.html': 'html', '.vue': 'vue', '.svelte': 'svelte',
};

/** Grammars we can actually parse in stage 3. Everything else inventories fine and extracts nothing. */
export const PARSEABLE = new Set(['python', 'javascript', 'typescript', 'tsx']);

const LOCKFILES = new Set([
  'package-lock.json', 'yarn.lock', 'pnpm-lock.yaml', 'npm-shrinkwrap.json',
  'poetry.lock', 'Pipfile.lock', 'uv.lock', 'pdm.lock', 'conda-lock.yml',
  'Cargo.lock', 'go.sum', 'composer.lock', 'Gemfile.lock', 'mix.lock', 'flake.lock',
]);

const STRUCTURAL_NAMES = new Set([
  'package.json', 'tsconfig.json', 'jsconfig.json', 'pyproject.toml', 'setup.py',
  'setup.cfg', 'Pipfile', 'environment.yml', 'Cargo.toml', 'go.mod', 'pom.xml',
  'build.gradle', 'CMakeLists.txt', 'Makefile', 'Justfile', 'Dockerfile',
  'docker-compose.yml', 'docker-compose.yaml', 'compose.yml', 'compose.yaml',
  'manifest.yaml', 'manifest.yml', 'alembic.ini', 'tox.ini', 'Procfile',
  'README.md', 'ARCHITECTURE.md', 'CONTRIBUTING.md', 'CLAUDE.md',
  'main.py', 'app.py', 'wsgi.py', 'asgi.py', '__main__.py', 'manage.py', 'conftest.py',
  'index.ts', 'index.js', 'cli.ts', 'cli.js', 'main.ts', 'main.js', 'server.ts', 'server.js',
]);

const VENDOR_SEGMENTS = new Set([
  'vendor', 'vendored', 'third_party', 'thirdparty', 'node_modules',
  '.venv', 'venv', 'site-packages', 'bower_components', 'external',
]);

const GENERATED_SEGMENTS = new Set([
  'dist', 'build', 'out', '__pycache__', '.next', 'coverage', 'htmlcov',
  'migrations', 'reports', 'generated', '_generated', 'gen', 'target', '.egg-info',
]);

const TEST_SEGMENTS = new Set(['test', 'tests', 'spec', 'specs', '__tests__', 'testing', 'e2e']);

const GENERATED_HEADER = /@generated|DO NOT EDIT|Code generated by|autogenerated|Auto-generated/i;

/** Languages a test can actually be written in. Prose in a `specs/` folder is a document. */
const CODE_LANGUAGES = new Set([
  'python', 'javascript', 'typescript', 'tsx', 'rust', 'go', 'ruby',
  'java', 'kotlin', 'c', 'cpp', 'shell', 'vue', 'svelte',
]);

/** `conftest.py` is a test fixture, not an entrypoint — test wins over structural. */
function looksLikeTest(base: string, segments: string[], language: string | null): boolean {
  const nameSaysTest =
    /^test_.*\.(py|rb)$/.test(base) ||
    /_test\.(py|go|rb|ts|js)$/.test(base) ||
    /\.(test|spec)\.(ts|tsx|js|jsx|mjs|cjs)$/.test(base) ||
    base === 'conftest.py';
  if (nameSaysTest) return true;
  // A path segment on its own only means "test" for code. `specs/design.md` is prose,
  // and calling it a test damps a document that may be the most valuable file in the tree.
  const codeish = language !== null && CODE_LANGUAGES.has(language);
  return codeish && segments.some((s) => TEST_SEGMENTS.has(s.toLowerCase()));
}

function looksGeneratedByName(base: string): boolean {
  return (
    /\.min\.(js|css)$/.test(base) ||
    /\.bundle\.js$/.test(base) ||
    /\.map$/.test(base) ||
    /_pb2(_grpc)?\.py$/.test(base) ||
    /\.pb\.go$/.test(base) ||
    /\.g\.dart$/.test(base) ||
    /^__init__\.pyc$/.test(base)
  );
}

/** Minimal gitattributes glob -> RegExp. Supports `*`, `**`, `?` and a leading `/` anchor. */
function globToRegExp(glob: string): RegExp {
  let g = glob.trim();
  const anchored = g.startsWith('/');
  if (anchored) g = g.slice(1);
  let out = '';
  for (let i = 0; i < g.length; i++) {
    const c = g[i]!;
    if (c === '*') {
      if (g[i + 1] === '*') { out += '.*'; i++; if (g[i + 1] === '/') i++; }
      else out += '[^/]*';
    } else if (c === '?') out += '[^/]';
    else out += c.replace(/[.+^${}()|[\]\\]/g, '\\$&');
  }
  return new RegExp(anchored ? `^${out}$` : `(^|/)${out}$`);
}

interface AttrRule { re: RegExp; generated: boolean; vendored: boolean }

/** The linguist markers the spec names explicitly — the repo telling us about itself. */
function readGitAttributes(repoAbs: string): AttrRule[] {
  const file = path.join(repoAbs, '.gitattributes');
  let text: string;
  try { text = fs.readFileSync(file, 'utf8'); } catch { return []; }
  const rules: AttrRule[] = [];
  for (const rawLine of text.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith('#')) continue;
    const parts = line.split(/\s+/);
    const pattern = parts[0];
    if (!pattern) continue;
    const attrs = parts.slice(1);
    const generated = attrs.includes('linguist-generated') || attrs.includes('linguist-generated=true');
    const vendored = attrs.includes('linguist-vendored') || attrs.includes('linguist-vendored=true');
    if (generated || vendored) rules.push({ re: globToRegExp(pattern), generated, vendored });
  }
  return rules;
}

function classify(
  relPath: string,
  base: string,
  ext: string,
  language: string | null,
  head: string,
  attrRules: AttrRule[],
  repoRelPath: string,
): { classification: Classification; signals: string[] } {
  const signals: string[] = [];
  const segments = path.posix.dirname(relPath).split('/').filter((s) => s && s !== '.');

  for (const rule of attrRules) {
    if (rule.re.test(repoRelPath)) {
      if (rule.vendored) { signals.push('gitattributes:linguist-vendored'); return { classification: 'vendored', signals }; }
      if (rule.generated) { signals.push('gitattributes:linguist-generated'); return { classification: 'generated', signals }; }
    }
  }

  if (LOCKFILES.has(base)) { signals.push(`lockfile-name:${base}`); return { classification: 'lockfile', signals }; }

  const vendorHit = segments.find((s) => VENDOR_SEGMENTS.has(s.toLowerCase()));
  if (vendorHit) { signals.push(`vendor-path:${vendorHit}/`); return { classification: 'vendored', signals }; }

  const genHit = segments.find((s) => GENERATED_SEGMENTS.has(s.toLowerCase()) || s.endsWith('.egg-info'));
  if (genHit) { signals.push(`generated-path:${genHit}/`); return { classification: 'generated', signals }; }
  if (looksGeneratedByName(base)) { signals.push(`generated-name:${base}`); return { classification: 'generated', signals }; }
  if (GENERATED_HEADER.test(head)) { signals.push('generated-header'); return { classification: 'generated', signals }; }

  if (looksLikeTest(base, segments, language)) { signals.push('test-path-or-name'); return { classification: 'test', signals }; }

  if (STRUCTURAL_NAMES.has(base) || /\.config\.(js|ts|mjs|cjs)$/.test(base) ||
      /^requirements.*\.txt$/.test(base) || relPath.startsWith('.github/workflows/')) {
    signals.push(`structural-name:${base}`);
    return { classification: 'structural', signals };
  }

  if (language && PARSEABLE.has(language)) { signals.push(`language:${language}`); return { classification: 'source', signals }; }
  if (language && ['rust', 'go', 'ruby', 'java', 'kotlin', 'c', 'cpp', 'shell', 'vue', 'svelte', 'css', 'html'].includes(language)) {
    signals.push(`language:${language}`);
    return { classification: 'source', signals };
  }

  signals.push(ext ? `data-ext:${ext}` : 'data-no-ext');
  return { classification: 'data', signals };
}

function gitFacts(repoAbs: string): { head: string | null; branch: string | null; commitCount: number } {
  const run = (args: string[]): string | null => {
    try {
      return execFileSync('git', ['-C', repoAbs, ...args], {
        encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'], maxBuffer: 64 * 1024 * 1024,
      }).trim();
    } catch { return null; }
  };
  const head = run(['rev-parse', 'HEAD']);
  const branch = run(['rev-parse', '--abbrev-ref', 'HEAD']);
  const count = run(['rev-list', '--count', 'HEAD']);
  return { head, branch, commitCount: count ? Number(count) : 0 };
}

/** Null-byte probe over the first 8KB — the same test git uses to call a file binary. */
function isBinary(buf: Buffer, len = buf.length): boolean {
  const n = Math.min(len, 8192);
  for (let i = 0; i < n; i++) if (buf[i] === 0) return true;
  return false;
}

const CHUNK = 1024 * 1024;

interface FileProbe {
  sha256: string;
  binary: boolean;
  /** decoded text, capped at maxReadBytes; empty for binaries */
  text: string;
  truncated: boolean;
  bytesRead: number;
}

/**
 * Hash the WHOLE file in chunks while keeping only the first `maxReadBytes` as text.
 *
 * Reading whole files into memory to hash them is fine until it isn't: the target here is
 * large repos, and a single oversized file would otherwise take the heap with it. The
 * content hash must still cover every byte — it is the cache key that makes a rename free
 * (spec §4), so hashing a prefix would silently collide edited files.
 */
function probeFile(abs: string, maxReadBytes: number): FileProbe {
  const hash = createHash('sha256');
  const buf = Buffer.allocUnsafe(CHUNK);
  const kept: Buffer[] = [];
  let keptBytes = 0;
  let total = 0;
  let binary = false;
  let checkedBinary = false;

  const fd = fs.openSync(abs, 'r');
  try {
    for (;;) {
      const n = fs.readSync(fd, buf, 0, CHUNK, null);
      if (n === 0) break;
      hash.update(buf.subarray(0, n));
      if (!checkedBinary) {
        binary = isBinary(buf, n);
        checkedBinary = true;
      }
      if (!binary && keptBytes < maxReadBytes) {
        const want = Math.min(n, maxReadBytes - keptBytes);
        kept.push(Buffer.from(buf.subarray(0, want)));
        keptBytes += want;
      }
      total += n;
    }
  } finally {
    fs.closeSync(fd);
  }

  return {
    sha256: hash.digest('hex'),
    binary,
    text: binary ? '' : Buffer.concat(kept).toString('utf8'),
    truncated: !binary && total > maxReadBytes,
    bytesRead: total,
  };
}

function countLines(text: string): number {
  if (text.length === 0) return 0;
  let n = 1;
  for (let i = 0; i < text.length; i++) if (text.charCodeAt(i) === 10) n++;
  if (text.charCodeAt(text.length - 1) === 10) n--;
  return n;
}

export interface InventoryOptions {
  /** hard ceiling on bytes read per file; larger files are hashed and sized but not line-counted */
  maxReadBytes?: number;
  followSymlinks?: boolean;
}

export function inventory(rootInput: string, opts: InventoryOptions = {}): Inventory {
  const started = Date.now();
  const root = path.resolve(rootInput);
  const maxReadBytes = opts.maxReadBytes ?? 8 * 1024 * 1024;

  const repos: RepoRef[] = [];
  const files: FileRecord[] = [];
  const skipped: Array<{ path: string; reason: string }> = [];
  const attrCache = new Map<string, AttrRule[]>();
  let dirsWalked = 0;
  let filesSeen = 0;
  let bytesRead = 0;

  const rel = (abs: string): string => {
    const r = path.relative(root, abs);
    return r === '' ? '' : r.split(path.sep).join('/');
  };

  /** Register a repo root if `dirAbs` holds a `.git`. Returns its scan-relative root path. */
  const maybeRepo = (dirAbs: string): string | null => {
    const dotGit = path.join(dirAbs, '.git');
    let st: fs.Stats;
    try { st = fs.lstatSync(dotGit); } catch { return null; }
    const facts = gitFacts(dirAbs);
    const ref: RepoRef = {
      root: rel(dirAbs), absRoot: dirAbs,
      head: facts.head, branch: facts.branch, commitCount: facts.commitCount,
      pointer: !st.isDirectory(),
    };
    repos.push(ref);
    attrCache.set(ref.root, readGitAttributes(dirAbs));
    return ref.root;
  };

  const walk = (dirAbs: string, currentRepo: string | null): void => {
    dirsWalked++;
    const discovered = maybeRepo(dirAbs);
    const repoRoot = discovered ?? currentRepo;

    let entries: fs.Dirent[];
    try { entries = fs.readdirSync(dirAbs, { withFileTypes: true }); }
    catch (e) { skipped.push({ path: rel(dirAbs), reason: `unreadable: ${(e as Error).message}` }); return; }

    for (const entry of entries) {
      const abs = path.join(dirAbs, entry.name);
      const relPath = rel(abs);

      if (entry.isSymbolicLink() && !opts.followSymlinks) {
        skipped.push({ path: relPath, reason: 'symlink' });
        continue;
      }

      if (entry.isDirectory()) {
        // `.git` itself is never content — but we already read its facts above.
        if (entry.name === '.git') continue;
        if (NEVER_DESCEND.has(entry.name)) {
          skipped.push({ path: relPath, reason: `not descended: ${entry.name}` });
          continue;
        }
        walk(abs, repoRoot);
        continue;
      }

      if (!entry.isFile()) continue;
      filesSeen++;

      let st: fs.Stats;
      try { st = fs.statSync(abs); } catch { skipped.push({ path: relPath, reason: 'stat failed' }); continue; }

      let probe: FileProbe;
      try { probe = probeFile(abs, maxReadBytes); } catch (e) {
        skipped.push({ path: relPath, reason: `unreadable: ${(e as Error).message}` });
        continue;
      }
      bytesRead += probe.bytesRead;

      const { sha256, binary } = probe;
      const ext = path.extname(entry.name).toLowerCase();
      const language = LANGUAGE_BY_EXT[ext] ?? null;

      if (binary) {
        files.push({
          path: relPath, repo: repoRoot ?? '', bytes: st.size, loc: 0,
          language: null, sha256, classification: 'data', signals: ['binary'], binary: true,
        });
        continue;
      }

      const tooBig = probe.truncated;
      const text = probe.text;
      // -1, never a guess: a truncated file's real line count is unknown, and ranking
      // treats -1 as zero size rather than pretending the prefix is the whole file.
      const loc = tooBig ? -1 : countLines(text);
      const head = text.slice(0, 2048);

      const repoAbs = repoRoot === null ? root : path.join(root, repoRoot);
      const repoRelPath = path.relative(repoAbs, abs).split(path.sep).join('/');
      const { classification, signals } = classify(
        relPath, entry.name, ext, language, head, attrCache.get(repoRoot ?? '') ?? [], repoRelPath,
      );
      if (tooBig) signals.push(`truncated-at:${maxReadBytes}`);

      files.push({
        path: relPath, repo: repoRoot ?? '', bytes: st.size, loc,
        language, sha256, classification, signals, binary: false,
      });
    }
  };

  walk(root, null);
  files.sort((a, b) => (a.path < b.path ? -1 : a.path > b.path ? 1 : 0));
  repos.sort((a, b) => (a.root < b.root ? -1 : a.root > b.root ? 1 : 0));

  return {
    root,
    repos,
    files,
    skipped,
    stats: {
      dirsWalked, filesSeen, filesRecorded: files.length, bytesRead,
      wallMs: Date.now() - started,
    },
  };
}
